apiVersion: networking.gke.io/v1alpha1
kind: ClusterDNS
metadata:
  name: default
spec:
  upstreamNameservers:
    - serverIP: 8.8.8.8 #{to change}
    - serverIP: 8.8.4.4 # {to change}
    - 
