apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml

configMapGenerator:
  - name: my-config
    literals:
      - RETENTION_TOTAL=7d
      - LIST_OF_PVC_NAMES=pvc-data-1,pvc-data-2
      - SCHEDULE=0 0 * * *
