apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-vmbackup
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: git
  git:
    auth: token
    branch: vmbackup
    dir: ./vmbackup
    period: 0s
    repo: https://github.com/psabhishekgoogle/gdctestmcd
    secretRef:
      name: github-vm-token
