apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntuhd
  namespace: mcdonaldstest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-block
  volumeMode: Block
