apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: boot-disk-pvc
  namespace: mcdonaldstest
spec:
  persistentVolumeClaim:
    claimName: boot-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boot-pvc
  namespace: mcdonaldstest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Or your storage class
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: data-disk-pvc
  namespace: mcdonaldstest
spec:
  persistentVolumeClaim:
    claimName: data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: mcdonaldstest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Or your storage class
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineType
metadata:
  name: custom-vm-type
  namespace: mcdonaldstest
spec:
  cpu: 2
  memory: 4Gi
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: my-vm-pvc
  namespace: mcdonaldstest
spec:
  osType: LINUX
  vmType: custom-vm-type
  disks:
  - boot: true
    virtualMachineDiskName: boot-disk-pvc
  - boot: false
    virtualMachineDiskName: data-disk-pvc
  networkInterfaces:
  - networkName: default
    default: true
  bootImage: projects/debian-cloud/global/images/family/debian-11
