apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/kust

patches:
  - target:
      kind: ConfigMap
      name: my-config
    patch: |-
      - op: replace
        path: /data/RETENTION_TOTAL
        value: 1d
      - op: replace
        path: /data/LIST_OF_PVC_NAMES
        value: dev-pvc-1,dev-pvc-2,dev-pvc-3
      - op: replace
        path: /data/SCHEDULE
        value: "*/5 * * * *"
